---
abstract: "install the CPAN dependencies of the\nFreecell Solver test suite."
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-FreecellSolver-Testing
provides:
  Task::FreecellSolver::Testing:
    file: lib/Task/FreecellSolver/Testing.pm
    version: v0.0.2
requires:
  Carp: 0
  Cwd: 0
  Data::Dumper: 0
  Digest::SHA: 0
  Env::Path: 0
  File::Path: 0
  File::Spec: 0
  Games::Solitaire::Verify: 0
  Games::Solitaire::Verify::Solution: 0
  IPC::Open2: 0
  List::MoreUtils: 0
  Storable: 0
  String::ShellQuote: 0
  Task::Test::Run::AllPlugins: 0
  Template: 0
  Test::Differences: 0
  Test::More: 0
  YAML::XS: 0
  base: 0
  lib: 0
  strict: 0
  warnings: 0
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v0.0.2
